#!/bin/bash
#
# Usage: toChar 
# 

# Stops execution if any command fails.
set -eo pipefail

boolToInt() {
    bool="$1"
    until=8
    if [[ ${#bool} -lt 8 ]]; then
        until=${#bool}
    fi
    sum=0
    multiplier=128
    for (( i=0; i<${#bool}; i++ )); do
        character=${bool:$i:1}
        if [[ "$character" == '*' ]]; then
            let sum=sum+multiplier
        fi
        let multiplier=multiplier/2
    done
    echo "$sum"
}

main() {
    input=$(cat)
    IFS=$'\n'
    echo "$input" | while read line; do
        #echo "$line"
        number=$(boolToInt "$line")
        printf "\x$(printf %x $number)"
    done
}

main "$@"
